MODEL:
  LAYERS: 10
  BLOCKS: 4
  KERNEL_SIZE: 2
  RESIDUAL_CHANNELS: 32
  DILATION_CHANNELS: 32
  SKIP_CHANNELS: 256
  END_CHANNELS: 256
  INITIAL_FILTER_WIDTH: 1
  BIAS: False
DATASET:
  DIRPATH: data/TIMIT/
  TARGET_LENGTH: 32
  QUANTIZATION_LEVELS: 256
TRAINING:
  BATCH_SIZE: 32
  SHUFFLE: True
  WORKERS: 8
  EPOCHS: 1
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.0
  TRAIN_VAL_SPLIT: 0.8
  CUDA: True
